### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by RDx55** [mkayen/DailyFBB-Engine#2]
This script is no longer working. It will not return any lineups.

I get the following when I run it

Script has started to run. Please wait a few minutes for lineup to generate.
0 | 0 | 0 | 0 | 0
0 | 0 | 0 | 0 | 0
0
0
0
undefined

**Comment by mkayen** [comment]
Yes, I'm aware of this. Will push some changes shortly.

**Comment by mkayen** [comment]
Changes have been made. All should be resolved here. Please pull in changes and confirm.

**Comment by RDx55** [comment]
It's still not working for me. 

I am now getting this error

Promise {
  _bitField: 0,
  _fulfillmentHandler0: undefined,
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined,
  _cancellationParent:
   Promise {
     _bitField: 1,
     _fulfillmentHandler0: [Function],
     _rejectionHandler0: undefined,
     _promise0: [Circular],
     _receiver0: undefined,
     _cancellationParent:
      Promise {
        _bitField: 1,
        _fulfillmentHandler0: undefined,
        _rejectionHandler0: undefined,
        _promise0: [Circular],
        _receiver0: undefined,
        _onCancelField: [Function],
        _branchesRemainingToCancel: 1 },
     _branchesRemainingToCancel: 1 } }
Player Data:
[]
Script has started to run. Please wait a few minutes for lineup to generate.
17 | 13 | 10 | 9 | 9
10 | 10 | 10 | 10 | 9
90000
100
0
undefined
